name             'my_cookbook'
maintainer       'MOV Company'
maintainer_email 'admin@mov.lt'
license          ''
description      'Installs/Configures my_cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'build-essential'
depends          'chef-client'
depends          'apt'
depends          'ntp'
depends          'apache2', '>= 1.0.4'
conflicts        'nginx'
